version: '3.9'

services:
  db:
    env_file: ./backend/internal/database/.env
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${DB_PORT}:5432'

  adminer:
    env_file: ./backend/internal/database/.env
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - '${ADMINER_PORT}:8080'
